---

- name : Install docker & docker-compose
  pip:
    name: 
      - docker
      - docker-compose
    state: present
    
- name: Pull repo 
  git:
    dest: "{{ deployment_path }}"
    repo: "{{ git_repository }}"
    version: "{{ git_branch }}"
    
    
- name: Launch compose
  docker_compose:    
    project_scr: "{{ deployment_path }}"
    build: true
    debug: true


    